name: codelessly_json_annotation
version: 4.9.0+1
description: >-
  Classes and helper functions that support JSON code generation via the
  `json_serializable` package.
repository: https://github.com/Codelessly/json_serializable.dart/tree/master/json_annotation
topics:
 - json
 - build-runner
 - json-serializable
 - codegen

environment:
  sdk: ^3.0.0

dependencies:
  collection: ">=1.17.0 <2.0.0"
  meta: ^1.4.0

dev_dependencies:
  dart_flutter_team_lints: ^2.0.0
# When changing JsonSerializable class.
#  build_runner: ^2.0.0
#  codelessly_json_serializable: any
